spring.application.name: kafka-streams-aggregate-sample

spring.cloud.stream.bindings.input:
  consumer:
    useNativeDecoding: false
  destination: balance-on-hand
  group: balance-on-hand-processor
spring.cloud.stream.bindings.output:
  producer:
    useNativeEncoding: false
  destination: balance-on-hand-summary-event

spring.cloud.stream.kafka.streams.binder:
#application.id: ${spring.application.name}
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
    commit.interval.ms: 1000

